Add functionality for book creating and deleting
bettercallazamat/react-bookstore pull request #3
Opened 2021-09-06 22:47 UTC by bettercallazamat

In this PR, I have connected the CREATE_BOOK and REMOVE_BOOK actions with the React component and made the page dynamic.

2021-09-06 23:26 UTC, rindrajosia requested changes
Hi, 

Good job so far!
There are some issues to revise before continuing to the next project but hang in there and read the comments below with care. You can do it! :muscle:


## Required Changes ♻️

- [ ] I got errors related to PropTypes when I open your APP. Keep in mind that PropTypes are a mechanism to ensure that components use the correct data type and pass the right data, and that components use the right type of props, and that receiving components receive the right type of props.
![1](https://user-images.githubusercontent.com/58552748/132265409-aa0e3525-0060-421b-9dde-dc00be796097.gif)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-09-06 23:26 UTC, rindrajosia commented on src/containers/BooksForm.js
> +    dispatch(createAction({ ...book, id: Math.floor(Math.random() * 100) }));
- [ ] [REQUIRED] you should `reset the STATE `once the book is created.  [screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone3/HandleSubmit.png)

2021-09-06 23:34 UTC, bettercallazamat commented
> Hi,
> 
> Good job so far!
> There are some issues to revise before continuing to the next project but hang in there and read the comments below with care. You can do it! 💪
> 
> ## Required Changes ♻️
> * [ ]  I got errors related to PropTypes when I open your APP. Keep in mind that PropTypes are a mechanism to ensure that components use the correct data type and pass the right data, and that components use the right type of props, and that receiving components receive the right type of props.
>   ![1](https://user-images.githubusercontent.com/58552748/132265409-aa0e3525-0060-421b-9dde-dc00be796097.gif)
> 
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

Could you give a hint on how can I check prop types correctly? Reason why I am asking, because when I use PropTypes.shape or book.object I am getting eslint errors.

2021-09-07 16:15 UTC, rindrajosia approved these changes
Hi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-09-07 16:16 UTC, merged